name: Test push

on:
  push:
    branches:
      - main
      - future

jobs:
  test_main:
    if: github.ref_name == 'main'
    uses: ./.github/workflows/test.yml
    with:
      source_ref: main
      firedrake_docker_version: dev-release
    secrets: inherit

  test_future:
    if: github.ref_name == 'future'
    uses: ./.github/workflows/test.yml
    with:
      source_ref: future
      firedrake_docker_version: dev-main
    secrets: inherit
