name: Test on push

on:
  push:
    branches:
      - main
      - future

jobs:
  setup:
    name: Determine Firedrake Docker version to use
    runs-on: ubuntu-latest
    outputs:
      firedrake_docker_version: ${{ steps.find.outputs.firedrake_docker_version }}
    steps:
      - id: find
        run: |
          if [ ${{ github.ref_name }} = 'main' ]; then
            echo "firedrake_docker_version=dev-release" >> "$GITHUB_OUTPUT"
          else
            test ${{ github.ref_name }} = 'future' || exit 1
            echo "firedrake_docker_version=dev-main" >> "$GITHUB_OUTPUT"
          fi

  test:
    needs: setup
    uses: ./.github/workflows/test.yml
    with:
      source_ref: ${{ github.ref_name }}
      firedrake_docker_version: ${{ needs.setup.outputs.firedrake_docker_version }}
    secrets: inherit
