name: Weekly main tests

on:
  schedule:
    # Scheduled for 0130 UTC on Monday mornings to detect bitrot
    - cron:  '30 1 * * 1'
jobs:
  test_main:
    uses: ./.github/workflows/test.yml
    with:
      source_ref: main
      firedrake_docker_version: dev-release
    secrets: inherit
