name: Weekly tests

on:
  schedule:
    # Scheduled for 0130 UTC on Monday mornings to detect bitrot
    - cron:  '30 1 * * 1'
    # Scheduled for 0430 UTC on Monday mornings to detect bitrot
    - cron:  '30 4 * * 1'
jobs:
  test_main:
    uses: ./.github/workflows/test.yml
    if: github.event.schedule == '30 1 * * 1'
    with:
      source_ref: main
      firedrake_docker_version: dev-release
    secrets: inherit

  test_future:
    uses: ./.github/workflows/test.yml
    if: github.event.schedule == '30 4 * * 1'
    with:
      source_ref: future
      firedrake_docker_version: dev-main
    secrets: inherit
