name: Weekly future tests

on:
  schedule:
    # Scheduled for 0430 UTC on Monday mornings to detect bitrot
    - cron:  '30 4 * * 1'
jobs:
  test_future:
    uses: ./.github/workflows/test.yml
    with:
      source_ref: future
      firedrake_docker_version: dev-main
    secrets: inherit
