name: Weekly tests

on:
  schedule:
    # Scheduled for 0330 UTC on Monday mornings to detect bitrot
    - cron:  '30 3 * * 1'

jobs:
  test_main:
    uses: ./.github/workflows/test.yml
    with:
      source_ref: main
      firedrake_docker_version: dev-release
    secrets: inherit

  test_future:
    uses: ./.github/workflows/test.yml
    with:
      source_ref: future
      firedrake_docker_version: dev-main
    secrets: inherit
